version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dev.dockerfile
    env_file:
      - .env
    ports:
    - 8080:3000
    volumes:
    - ./src:/home/app/src
    - ./public:/home/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
